"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Context from "@/lib/context";
import LayoutWrapper from "./layoutWrapper";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Satsang</title>
      <link rel="manifest" href="/manifest.json" />{" "}
      <link rel="apple-touch-icon" href="/favicon.jpg"></link>
      <meta name="theme-color" content="#fff" />
      <link rel="icon" type="image/x-icon" href="/favicon.jpg"></link>
      <body
        className={inter.className}
        style={{
          background:
            "url(https://images.hdqwalls.com/wallpapers/abstract-blur-dark-5k-x9.jpg)",
          backgroundRepeat: "no-repeat",
          backgroundAttachment: "fixed",
          backgroundSize: "cover",
        }}
      >
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
